# nixpacks.toml

[phases.setup]
nixPkgs = [
  "nodejs_22",
  "openssl",
  "python3",
  "pkg-config"
]

[phases.install]
cmds = [
  "npm install",
  "npm audit fix",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"